### ISSUE TITLE
Using fsspec/dropboxdrivefs makes Kedro DataSet gobble up the first directory level

### ISSUE THREAD

**Issue by mjmare** [fsspec/dropboxdrivefs#8]
Please see: https://github.com/kedro-org/kedro/issues/1262
TIA

**Comment by MarineChap** [comment]
Hello, 
Not sure how to answer you... I am not using myself kedro and I don't know how it uses fsspec. I don't even know what was your own use-case. Could you give me more info or a way to replicate this behavior without the kedro lib ? 

I am always happy to develop new features per request or help with a bug but I unfortunately don't have the time to investigate myself with so little info.
Have a good day.

**Comment by mjmare** [comment]
Hi @MarineChap, I can understand that. 
What I think is happening is that Kedro just passed the file path to fsspec.
For dropbox this might be dropbox://testing/activiteiten.pickle, in which case the file is stored at <my dropbox folder>/activiteiten.pickle. The testing part is ignored. 
But for say S3 this might be: s3://bucket/testing/activiteiten.pickle, in which case the resulting file path is /testing/activiteiten.pickle in the correct bucket. 
Maybe this behaviour is compatible with the fsspec spec but I didn't expect it ;-)

**Comment by MarineChap** [comment]
Are you talking about uploading or downloading files ? The file stored at /activiteiten.pickle is in local after download or in dropbox after upload ?
Do you think you could point me what part of the code in kedros you are using for this part please?

**Comment by mjmare** [comment]
Oops, I had 
```
<my dropbox folder>/activiteiten.pickle
```
in my comment but GH removed the text between brackets. 

In Kedro one declares data sources in a data catalog in YAML: https://kedro.readthedocs.io/en/stable/05_data/01_data_catalog.html

E.g.
```
activiteiten_extra_dropbox:
  layer: intermediate
  type: pickle.PickleDataSet
  filepath: dropbox://dummy/testing/activiteiten_extra.pickle
  credentials: dropbox


activiteiten_extra_upload:
  layer: intermediate
  type: pickle.PickleDataSet
  filepath: s3://achn-testbucket/testing/activiteiten_extra.pickle
  credentials: s3_do 
```
They can be read and write.
